#!/bin/bash

input="test_key_responses.csv"
while IFS=',' read -r f1 f2
do
  adduser --disabled-password --force-badname --gecos student "$f1"
  mkdir /home/"$f1"
  chown "$f1" /home/"$f1"/
  mkdir /home/"$f1"/.ssh
  chown "$f1" /home/"$f1"/.ssh
  echo "$f2" > /home/"$f1"/.ssh/authorized_keys
  chown "$f1" /home/"$f1"/.ssh/authorized_keys
  #chmod 755 /home/"$f1"/.ssh/authorized_keys
  cp /home/dave/.unreadable /home/"$f1"/
  chown "$f1" /home/"$f1"/.unreadable
  echo "echo "" " >> /home/"$f1"/.profile
  echo "/bin/userhash" >> /home/"$f1"/.profile
  echo "echo "" " >> /home/"$f1"/.profile
  usermod -a -G competitors "$f1"
  echo "User: $f1" 
  echo "Key: $f2"
done < "$input"
